if (!("Settings" in ::AlternateDifficulties))
{
	::AlternateDifficulties.Settings <- {};
}

::AlternateDifficulties.Settings.register <- function()
{
	local general = ::AlternateDifficulties.Mod.ModSettings.addPage("General");
	local developer = ::AlternateDifficulties.Mod.ModSettings.addPage("Developer Options");
	local developerLab = ::AlternateDifficulties.Mod.ModSettings.addPage("Developer Test Lab");

	general.addRangeSetting(
		"CustomDifficultyMultiplier", 1.10, 0.85, 2.00, 0.01,
		"Custom Enemy Difficulty",
		"1.15 is Legends' highest native enemy-budget multiplier (Expert). Higher values increase only this mod's encounter budget; they do not enable Legendary enemy stats, perks, poison effects, or AI. Changes affect newly calculated encounters only; existing enemy parties do not resize."
	);

	local debugLogging = developer.addBooleanSetting(
		"DebugLogging", true,
		"Debug Logging",
		"Write Alternate Difficulties diagnostic lines to log.html."
	);

	debugLogging.addCallback(function(_data = null)
	{
		::AlternateDifficulties.Settings.configureDebugLogging();
	});

	developerLab.addBooleanSetting(
		"EnableDeveloperTestLab", false,
		"Enable Developer Test Lab",
		"Enables the explicit test buttons below. This is intended for a disposable new campaign and never runs automatically."
	);
	developerLab.addRangeSetting(
		"TestRosterLevel", 6, 1, 99, 1,
		"Test roster level",
		"Target level for the explicit Set All Roster Levels button. Brothers already at or above this level are not lowered."
	);
	developerLab.addRangeSetting(
		"TestCrownsAmount", 5000, 100, 50000, 100,
		"Test crowns amount",
		"Exact crowns granted by the explicit Grant Crowns button."
	);
	developerLab.addRangeSetting(
		"TestDaysToAdvance", 100, 1, 365, 1,
		"Test days to advance",
		"Calendar days added by the explicit button. This test-only jump does not replay wages, healing, events, contracts, or other daily processing for every skipped day."
	);
	developerLab.addEnumSetting(
		"TestContractType", "Drive Off Brigands",
		["Drive Off Brigands", "Investigate Cemetery", "Hunt Webknechts", "Hunt Unholds", "Drive Off Nomads"],
		"Test contract type",
		"A normal settlement contract to create through its native faction action when its normal world requirements are met."
	);
	developerLab.addEnumSetting(
		"TestContractSkull", 2, [1, 2, 3, 4],
		"Test contract skull",
		"The fixed 1-4 skull offer applied to the one normal contract generated by the explicit button."
	);
	developerLab.addButtonSetting(
		"ApplyTestRosterLevel", null,
		"Set All Roster Levels",
		"Explicit action: raises current roster brothers to Test roster level. It does not grant equipment or crowns."
	).addCallback(function(_data = null)
	{
		::AlternateDifficulties.DeveloperTestLab.applyRosterLevel();
	});
	developerLab.addButtonSetting(
		"GrantMidTierLoadout", null,
		"Grant Mid-tier Loadout",
		"Explicit action: adds a non-named armor, helmet, axe, hammer, sword, flail, and polearm per current brother to the stash."
	).addCallback(function(_data = null)
	{
		::AlternateDifficulties.DeveloperTestLab.grantMidTierLoadout();
	});
	developerLab.addButtonSetting(
		"GrantTestCrowns", null,
		"Grant Crowns",
		"Explicit action: grants Test crowns amount exactly once for this button press."
	).addCallback(function(_data = null)
	{
		::AlternateDifficulties.DeveloperTestLab.grantCrowns();
	});
	developerLab.addButtonSetting(
		"AdvanceTestCampaignDays", null,
		"Advance Campaign Days",
		"Explicit action: permanently advances the disposable campaign calendar by Test days to advance. It only works outside tactical combat and skips ordinary per-day processing for the skipped period."
	).addCallback(function(_data = null)
	{
		::AlternateDifficulties.DeveloperTestLab.advanceCampaignDays();
	});
	developerLab.addButtonSetting(
		"GenerateSelectedTestContract", null,
		"Generate Selected Normal Contract",
		"Explicit action: creates exactly one selected normal contract at the current settlement, only when the game's native action says it is currently legal."
	).addCallback(function(_data = null)
	{
		::AlternateDifficulties.DeveloperTestLab.generateSelectedNormalContract();
	});

	::AlternateDifficulties.Settings.configureDebugLogging();
}

::AlternateDifficulties.Settings.isDebugEnabled <- function()
{
	return ::AlternateDifficulties.Mod.ModSettings.getSetting("DebugLogging").getValue();
}

::AlternateDifficulties.Settings.configureDebugLogging <- function()
{
	local enabled = ::AlternateDifficulties.Settings.isDebugEnabled();
	::AlternateDifficulties.Mod.Debug.setFlag("default", enabled);

	if (enabled)
	{
		::AlternateDifficulties.Mod.Debug.printLog("[AlternateDifficulties] debug logging enabled");
	}
}
